### ISSUE TITLE
Docker tooling for development

### ISSUE THREAD

**Issue by sjsrey** [spatialucr/geosnap#101]
- [ ]  Handle os specific [directories for quilt](https://github.com/ActiveState/appdirs) when mounting host volumes
- [ ] Add other dependencies (testing, etc)
- [ ] swap mamba for conda (where possible)
- [ ] use requirements files in Dockerfile

**Comment by knaaptime** [comment]
with tobler stabilized and mamba working better now, I think this is no longer an issue
