### ISSUE TITLE
notebooks are not running successfully

### ISSUE THREAD

**Issue by weikang9009** [spatialucr/geosnap#107]
Example notebooks are not running successfully. For example, [03_modeling_neighborhood_types.ipynb](https://github.com/spatialucr/geosnap/blob/master/examples/03_modeling_neighborhood_types.ipynb) runs into the following error:
<img width="1279" alt="image" src="https://user-images.githubusercontent.com/7359284/62404379-9d217880-b548-11e9-9b76-250163003a5c.png">

**Comment by knaaptime** [comment]
i'm working on redoing the notebooks to reflect the new api

**Comment by sjsrey** [comment]
This is fixed with #108
