### ISSUE TITLE
(bug) inconsistency of localizing quilt3 data sets

### ISSUE THREAD

**Issue by weikang9009** [spatialucr/geosnap#116]
In the `data` module, an Import error is given if several data sets are not stored locally using the function `data.store_census`. The inspected data sets include `blocks_2010` and `blocks_2000` which are not localized by [function `data.store_census`](https://github.com/spatialucr/geosnap/blob/master/geosnap/data/data.py#L347). 

Thus, even if users called `data.store_census` before, they will still run into the Import error.

 We should resolve this bug by making a choice in terms of whether to localize `blocks_2010` and `blocks_2000` for general users as they are pretty large.

**Comment by knaaptime** [comment]
where are you getting an error? as of #111, you should receive a warning that you're using streaming data, if you haven't called the `store_census` function

I'd intended to provide two additional functions (`store_blocks_2000` and `store_blocks_2010`) since each of those total about 5gb

**Comment by weikang9009** [comment]
If you look at the function [data.store_census](https://github.com/spatialucr/geosnap/blob/master/geosnap/data/data.py#L347), it is not storing the two large data sets. But the  [data import ](https://github.com/spatialucr/geosnap/blob/master/geosnap/data/data.py#L43) is checking on these two data sets.

**Comment by knaaptime** [comment]
yeah, it should be a different check since `store_census` shouldn't download blocks

**Comment by knaaptime** [comment]
resolved by #117
