### ISSUE TITLE
consider move to mkdocs

### ISSUE THREAD

**Issue by knaaptime** [spatialucr/geosnap#140]
i struggle with both rst and sphinx, so considering moving to [mkdocs](https://mkdocs.readthedocs.io/en/stable/) instead. seems pretty straightforward but wanted to get others opinions

**Comment by knaaptime** [comment]
the major downside is it appears much harder to do [autodocumentation](https://github.com/restaction/mkdocs-autodoc)

**Comment by weikang9009** [comment]
I am not familiar with `mkdocs` and won't be able to provide constructive suggestions.

**Comment by sjsrey** [comment]
I understand the motivation, but economies of scope would argue for sticking with sphinx rst since all the other packages in pysal use it.

**Comment by knaaptime** [comment]
i continue to loathe rst, but i agree its still the path of least resistance
