### ISSUE TITLE
include tests for example notebooks

### ISSUE THREAD

**Issue by knaaptime** [spatialucr/geosnap#159]
we should setup the CI to test that the example notebooks execute. This should be pretty straightforward with [nbconvert](https://nbconvert.readthedocs.io/en/latest/usage.html#notebook-and-preprocessors) (and might be a pattern we want to adopt more broadly in pysal?)

**Comment by weikang9009** [comment]
Sounds like a good idea!

**Comment by knaaptime** [comment]
resolved by #158

**Comment by knaaptime** [comment]
alternatively, we could setup travis on the [user guide](http://github.com/spatialucr/geosnap-guide) repo and run the notebook tests there instead

running notebooks as part of the main source code test suite ensures that the examples are always working for the latest codebase but it does add 10-15 minutes to the testing time (for ~30 min total run time)

If we run them as part of the user guide, then its possible the guide can become out of sync with the codebase
