### ISSUE TITLE
Release on Conda?

### ISSUE THREAD

**Issue by adamkgoldfarb** [spatialucr/geosnap#186]
Hello! Eagerly watching this repo as I'm interested in applications to education-- specifically, school districts. You could see how segregation, neighborhood identification, etc. can be applied! Two questions:
1. I assume that this is meant for development installs only per the README, as opposed to conda installs, at least until the first release. Is that correct?
2. Do you plan to subsume the segregation module from PySAL within this module at some point in the future? What's the relationship between geosnap and PySAL and friends?
Thanks for all the work you do!

**Comment by knaaptime** [comment]
awesome, cant wait to see what you do with the package, and thanks for the kind words. tl;dr: the conda release is coming soon. The blocking issues are tracked in #170

1. currently, yes, the development install is the way to go. Dont bother with the pip release, its about a year old and way, way behind. 
2. this is actually relevant to the release schedule so a handful of sub-points:
	- the geosnap devs are a subset of the pysal devs, so the relationship is close :)
	- the pysal packages are general-purpose whereas geosnap focuses on space-time neighborhood analysis and wraps several pysal components for a more convenient api when working with those data structures. The good news is that if there's a feature you really need, you can access it by dropping into the pysal packages, but it will take a bit more code. The bad news is sometimes we have new features in branches of geosnap that need to wait on other packages before they can be released, which is the case now... We're on the brink of releasing [tobler](https://github.com/pysal/tobler) which is the last dependency that needs to be on conda before we can release geosnap.
	- we'd already raised the idea of including segregation analytics in #77, so its good to have a vote that helps orient the roadmap. Is there a particular feature in `segregation` that you're most interested in? I'm working on some segregation projects now, so now that I know it'll be useful elsewhere i'll try to make sure that code gets integrated here sooner than later (though it's unlikely to make it into the first conda release)

**Comment by adamkgoldfarb** [comment]
Great, I'll subscribe to #170 and do a dev release if I am so inclined! 

No great urgency on the segregation integration, but the [demo code here](https://github.com/pysal/segregation/blob/master/notebooks/multiscalar_segregation_profiles.ipynb) is of interest-- it's probably not helpful to say "segregation.spatial" and "segregation.network" because that covers a lot, but the entropy measures are probably what I'll start with.

Thanks for all your great work-- following closely!

**Comment by knaaptime** [comment]
cool, you're in luck because that will be the first thing in from `segregation` :)
