### ISSUE TITLE
multiplatform testing

### ISSUE THREAD

**Issue by knaaptime** [spatialucr/geosnap#198]
I ran into a bunch of new issues releasing geosnap on conda-forge because of idiiosyncrasies with windows. Windows testing is still alpha in travis (i havent actually gotten a windows vm on travis to *boot*), but I started a [new config](https://github.com/knaaptime/geosnap/blob/testing/.travis.yml) that I think should work

**Comment by sjsrey** [comment]
Exploring moving to github actions:

- [ ] [use secrets for remote secure remote datasets](https://help.github.com/en/actions/configuring-and-managing-workflows/creating-and-storing-encrypted-secrets)

**Comment by sjsrey** [comment]
#219

**Comment by sjsrey** [comment]
Once #219 is merged, we are covering Ubuntu and Mac OSX.

**Comment by knaaptime** [comment]
resolved by #222
