### ISSUE TITLE
Google Colab pip install issue

### ISSUE THREAD

**Issue by nonoumasy** [spatialucr/geosnap#206]
Error message here:

Collecting rtree
  Downloading https://files.pythonhosted.org/packages/56/6f/f1e91001d5ad9fa9bed65875152f5a1c7955c5763168cae309546e6e9fda/Rtree-0.9.4.tar.gz (62kB)
     |████████████████████████████████| 71kB 9.0MB/s 
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.

**Comment by knaaptime** [comment]
you cant install `rtree` with pip (see, e.g. [here](https://gis.stackexchange.com/questions/337689/geopandas-overlay-doesnt-work-in-google-colaboratory-this-return-attributeerr))

but you can use `!apt-get install -y python-rtree`  then you should be able to pip install `geosnap`

**Comment by nonoumasy** [comment]
thanks. I tried this before but then I get this error message...
----> 1 import geosnap
....
TypeError: _list_packages() missing 1 required positional argument: 'registry'

**Comment by knaaptime** [comment]
thats because of #201 

`pip install quilt3==3.1.8` should solve it

**Comment by nonoumasy** [comment]
Thanks that works. The import took about 1 minute and there was one error:
ERROR: tobler 0.2.1 has requirement quilt3==3.1.8, but you'll have quilt3 3.1.10 which is incompatible.

But the package did load so it did work.

Also , when...

from geosnap import datasets, 
I got this message( I assume its just a warning and not an error).
/usr/local/lib/python3.6/dist-packages/geosnap/_data.py:121: UserWarning: Unable to locate local census data. Streaming instead.
If you plan to use census data repeatedly you can store it locally with the data.store_census function for better performance.

anyway, thanks. now, I can dig into geosnap.

**Comment by knaaptime** [comment]
👍 let us know if you run into anything else
