### ISSUE TITLE
GHA for conda-forge?

### ISSUE THREAD

**Issue by jGaboardi** [spatialucr/geosnap#224]
@knaaptime Awesome job the last few days getting the [PyPI upload GHA](https://github.com/spatialucr/geosnap/blob/master/.github/workflows/upload_package.yml) working. I am curious how this will affect the re-up of `conda-forge` versioning. Specifically, (1) will the `conda-forge` bot continue making automated PRs if the feedstock version doesn't match the PyPI version; and (2) will (could?) a new GHA be created to accomplish this.

**Comment by knaaptime** [comment]
i think the answer to 1 is yes, i'd expect the condabot to still keep pinging recipe maintiners each time a new pypi release gets pushed. 2 would be pretty interesting though. That would remove the need to double check the dependency changes each time (which can be a real pain)

**Comment by knaaptime** [comment]
p.s., the only stuff i'm tinkering with now is very geosnap-specific, so we should probably start copying over the base logic to the submod template

**Comment by jGaboardi** [comment]
It would be super neat to have that as a [`jobs.<job_id>.needs`](https://help.github.com/en/actions/reference/workflow-syntax-for-github-actions#jobsjob_idneeds) following the PyPI publishing in the same workflow.

**Comment by knaaptime** [comment]
should we close this given the new auto-merge functionality in conda-forge?

**Comment by jGaboardi** [comment]
Yup!
