### ISSUE TITLE
release action not implemented upstream

### ISSUE THREAD

**Issue by knaaptime** [spatialucr/geosnap#228]
for some reason, the new [publishing workflow](https://github.com/knaaptime/geosnap/blob/master/.github/workflows/upload_package.yml) only seems to be active on my fork...?

**Comment by knaaptime** [comment]
nvm. the tag needs to be pushed upstream explicitly

**Comment by jGaboardi** [comment]
It looks like the `tags` aren't making it over. When you were troubleshooting that workflow were you doing tagged commits on your `knaaptime/geosnap`, then merging into `spatialucr/geosnap`? Maybe try a direct tagged commit to `spatialucr/geosnap`.

**Comment by knaaptime** [comment]
of course, now this release is broken because the workflow on my fork already published 0.3.0 on pypi 🙃
