### ISSUE TITLE
import fails with `AttributeError: module 'sklearn.metrics' has no attribute 'calinski_harabaz_score'`

### ISSUE THREAD

**Issue by knaaptime** [spatialucr/geosnap#231]
this is a known issue in `spenc` and should be resolved shortly. The short term fix is to downgrade to scikit-learn 0.22, e.g. `conda install scikit-learn=0.22`

**Comment by knaaptime** [comment]
at the package level, this is resolved by #233. At a function level, this needs a new spenc release, but the fix has already been merged upstream

**Comment by suhanmappingideas** [comment]
Thank you so much! I will try it again.

**Comment by abhiag2018** [comment]
Another way is to just do a `import sklearn.metrics`. This resolves the issue even for the 0.23.1 version!
