### ISSUE TITLE
Harmonizing a community with areal interpolation

### ISSUE THREAD

**Issue by suhanmappingideas** [spatialucr/geosnap#244]
I just realized that the use of areal interpolation for data like median household income, median monthly housing cost,  and median housing value, does not make sense. In this case, what method do you recommend for the data harmonization of the median value?

Thank you so much in advance.

**Comment by sjsrey** [comment]
See the distinction between *extensive* and *intensive* variables [here](https://github.com/pysal/tobler/blob/master/notebooks/areal.ipynb).
