### ISSUE TITLE
deleting old stored census/ltdb data

### ISSUE THREAD

**Issue by stfran22** [spatialucr/geosnap#301]
I'm trying to figure out where data are stored locally when running store_census() or store_ltdb. I'd like to locate the files on my machine so I can delete them if I don't intend to use them again.

Steve

**Comment by knaaptime** [comment]
(maybe both should be on `datasets`, maybe both `io`, im not sure)

**Comment by stfran22** [comment]
Gotcha. I found the path by just searching “LTDB” in my C: drive and found it in a hidden folder. It was essentially:

C:/Users/<username>/AppData/geosnap/geosnap

I appreciate the quick response.

Steve
