### ISSUE TITLE
quilt3 error on fresh python 3.9 install

### ISSUE THREAD

**Issue by sjsrey** [spatialucr/geosnap#317]
After installing from the latest conda-forge in a fresh environment:

![Screenshot from 2021-11-18 13-48-12](https://user-images.githubusercontent.com/118042/142502264-dbfbf9b3-8142-4ad0-95fc-964313594955.png)

**Comment by knaaptime** [comment]
can you check quickly which version of quilt3 got installed?

jsonschema is [pinned](https://github.com/conda-forge/quilt-feedstock/blob/master/recipe/meta.yaml) in the latest quilt conda-forge recipe. We don't pin to a minimum quilt version in geosnap, so its possible we need to set quilt3>=3.6

**Comment by knaaptime** [comment]
could we take a look at your `conda list` in that environment?

**Comment by sjsrey** [comment]
This will fix it:
```
conda install quilt3=3.6 -c conda-forge
```
