### ISSUE TITLE
User authentication

### ISSUE THREAD

**Issue by sjsrey** [spatialucr/geosnap#41]
OSNAP web interface will need to allow for account generation for users via the web, and isolation of user created data.

This is related to [#40](https://github.com/spatialucr/osnap/issues/40).

**Comment by sjsrey** [comment]
Possible ideas for authentication models might follow [tljh](https://the-littlest-jupyterhub.readthedocs.io/en/latest/index.html)

**Comment by knaaptime** [comment]
is this still something we want to target with the new structure, or should we close and regroup on this?
