### ISSUE TITLE
add a private function that loads all geoms into memory

### ISSUE THREAD

**Issue by knaaptime** [spatialucr/geosnap#49]
queries on the web-based interface are slow, so it would be useful to add a function that loads all the necessary geoms into memory so they dont need to be created at each instantiation of Community

**Comment by suhanmappingideas** [comment]
here is your reference for the performance comparison. I queried the same data: % hispanic, Albertiville ( cbsafips="10700"), AL in 1990 by using the current server side program of LNE and OSNAP

1. The current server-side program of LNE
The current osnap: http://sarasen.asuscomm.com/LNE/python/getLNAnalysis.py?&year=1990&state=01%20IL&metro=10700&codes=1-03%20hispXX

2. OSNAP
http://osnap.cloud/~suhan/osnap/python/osnap_example.py
