### ISSUE TITLE
parameter description of Kmeans

### ISSUE THREAD

**Issue by suhanmappingideas** [spatialucr/geosnap#51]
I think that you have been working on it. But it would be really nice to add descriptions of all parameters for Kmeans in the near future. I was looking at the page below:

http://osnap.cloud/~suhan/osnap/osnap/doc/_build/html/generated/osnap.analyze.analytics.kmeans.html#osnap.analyze.analytics.kmeans

**Comment by knaaptime** [comment]
I'm looking into whether sphinx can automatically generate this documentation as well, but keep in mind that the classic clustering algos are all sklearn models, so in the meantime you can check those [docs](https://scikit-learn.org/stable/modules/classes.html#module-sklearn.cluster)

**Comment by knaaptime** [comment]
i also think this is why [dash](https://dash.plot.ly/) is a good option.
