### ISSUE TITLE
add tests

### ISSUE THREAD

**Issue by knaaptime** [spatialucr/geosnap#66]
We need to add tests for the following

~~- [x] Community plotting~~ plotting directly is a lot easier with the new structure since geoms are attached, but should we still try and implement top-level plotting?
- [x] geolytics importer
- [x] `from_lodes` constructor
- [x] `from_geodataframes` constructor
- [x] `from_census` constructor
- [x] harmonize functionality
- [x] Transition class (using Community as input)
- [ ] alternative distance calcs for Sequence class (markov, arbitrary, trans)

**Comment by knaaptime** [comment]
whats should we test for in a `Transition` class?

**Comment by knaaptime** [comment]
@weikang9009 could you help me brainstorm on this a bit?

**Comment by weikang9009** [comment]
Sure. We can do that this afternoon?
