### ISSUE TITLE
add metadata to existing datasets

### ISSUE THREAD

**Issue by sjsrey** [spatialucr/geosnap#68]
It would be helpful to document the original source for the [cbsa](
https://github.com/spatialucr/osnap/tree/master/osnap/data) definitions as these can change over time and we may need to cross-reference different time slices.

For example, we don't have parquet files for the following:

  - 41900 San Germán-Cabo Rojo, PR Metropolitan Statistical Area
  - 41980 San Juan-Caguas-Guaynabo, PR Metropolitan Statistical Area
  - 39140 Prescott, AZ Metropolitan Statistical Area
  - 38660 Ponce, PR Metropolitan Statistical Area
  - 10380 Aguadilla-Isabela-San Sebastián, PR Metropolitan Statistical Area
  - 11640
  - 32420 Mayagüez, PR Metropolitan Statistical Area
  - 25020 Guayama, PR Metropolitan Statistical Area
  - 19380 Dayton, OH Metropolitan Statistical Area

It makes sense that ltdb is not covering PR areas, but the AZ, OH and 11640 are less clear why they are not in the data.

**Comment by knaaptime** [comment]
thats a good point. The shape data come directly from census, but the table that osnap refers to as `cbsa` is the county crosswalk, probably from [here](http://www.nber.org/cbsa-msa-fips-ssa-county-crosswalk/cbsatocountycrosswalk.csv)

**Comment by knaaptime** [comment]
rather than storing the CBSA crosswalk, it might be better to just read it directly when necessary (like we do with the inflation table)

the benefits would be
1.  the documentation is implicit since the URL defines the original source (though we'd want to document explicitly as well)
2.  we could provide methods for users to call MSAs as defined in other years


[2019 cbsa-county definitions](http://www.nber.org/cbsa-msa-fips-ssa-county-crosswalk/2019/FY%202019%20FR%20County%20to%20CBSA%20Crosswalk.txt)

**Comment by sjsrey** [comment]
And an older source for [2003 cbsa definitions](https://www.census.gov/population/estimates/metro-city/0312msa.txt)

**Comment by knaaptime** [comment]
workflow:

1.  store "appropriate version in `osnap` repo
2.  when user calls a dataset, osnap checks the canonical dataset by downloading from the URL
3.  `osnap` checks to see whether stored version matches canonical version
4.  if versions don't match, raise a warning, etc.

**Comment by knaaptime** [comment]
if we're checking the dataset integrity with each use, is there any real use in caching it?

**Comment by knaaptime** [comment]
https://github.com/quiltdata/open-data-registry

**Comment by knaaptime** [comment]
we should use [this](https://www.census.gov/geographies/reference-files/time-series/demo/metro-micro/delineation-files.html) source. It might be best to always grab from the web like we do for the inflation adjustment table, though this would be used more and more prone to failure if the census api goes down. That would also mean you always need an internet connection to make MSA queries

**Comment by knaaptime** [comment]
should be resolved by #215 but give it a look

**Comment by knaaptime** [comment]
https://spatialucr.github.io/geosnap/data.html
