### ISSUE TITLE
include segregation analytics

### ISSUE THREAD

**Issue by knaaptime** [spatialucr/geosnap#77]

**Comment by knaaptime** [comment]
@renanxcortes since a `Community` already has a temporal structure, I'm thinking we can add some wrappers for temporal segregation analytics

**Comment by renanxcortes** [comment]
Ok, I'm +1 for that! The Idea would be passing a `Community` to "segregation wrappers" and generates a "segregation profile" of the Community? Could we draft this in more details next week?

**Comment by knaaptime** [comment]
exactly

**Comment by renanxcortes** [comment]
Ok, sounds good!

**Comment by knaaptime** [comment]
a community-based segregation profile with an argument (temporal=True) that will build the profile for each time period present in the Community
