### ISSUE TITLE
add plotting for transition matrices

### ISSUE THREAD

**Issue by knaaptime** [spatialucr/geosnap#83]
work on the tobler flow mapping paper reminds me of some network plots of the markov tranistion matrices I put together for the old gentrification paper

![image](https://user-images.githubusercontent.com/4213368/57802805-a0f0ec00-770b-11e9-957c-fa594a79491e.png)

It would be good to include a method for generating these as part of the `vizualize` module. The plots themselves can be generated with networkx which is already a dependency because of region. You can get much better layouts if you have pygraphviz installed, so this would probably induce a soft dependency

actually, since this is just a plot of the transition matrices, might this be better placed in giddy @weikang9009 ? along with, say, a heatmap plotting method too?

**Comment by weikang9009** [comment]
Sounds nice. I would prefer the viz function of the transition matrix to be placed in geosnap for now since we do not need to add more dependencies.

**Comment by knaaptime** [comment]
cool, thanks for the feedback. I'll work on it and ping you in the PR
