### ISSUE TITLE
add pooling option to cluster analytics

### ISSUE THREAD

**Issue by knaaptime** [spatialucr/geosnap#84]
we need to provide flexibility for how time is handled in the clustering process. 

- sometimes we want to pool the whole time series and standardize to the average for all times				
- sometimes we want to pool the time series and standardize within each decade
- sometimes we want to cluster each time period individually 

We need to provide arguments in the cluster functions to support each of these options

**Comment by knaaptime** [comment]
this is a quick if/then that would only take a few lines to implement, but the holdup is really the API terminology. The concept is we might want to scale relative to the pooled (global) mean or relative to each time period (local), each of which would result in different clusters/dynamics

`pooling` with options like `local` and `global` seems pretty opaque to me and as a new user I'd have no idea what that means. Anyone have an idea for a moree descriptive option?

**Comment by knaaptime** [comment]
we have a `scaler` argument, so maybe this would be `pooled_scaling` = either `relative` or `absolute`?

**Comment by weikang9009** [comment]
This is a good point and would be very useful to end-users. In `giddy`, spatial Markov modeling is contingent on a similar issue concerning the time dimension - whether (1) to discretize the pooled income values based on the same cutoffs, or (2) to discretize the cross-sectional income values based on the cutoffs defined for each time period. Parameter `fixed` is used for controlling the behavior of the discretization - it is (1) True or (2) False. 

I suggest using a combination of `pooled` and `fix`:
1. `pooled=True` and `fix=True`: sometimes we want to pool the whole time series and standardize to the average for all times
2. `pooled=True` and `fix=False`: sometimes we want to pool the time series and standardize within each decade
3.  `pooled=False`:  sometimes we want to cluster each time period individually

**Comment by knaaptime** [comment]
smart. i definitely like the idea of achieving this flexibility with two arguments. It would also be good to keep consistency with giddy, but i still lean toward something like `fixed_scale` so its just a bit more descriptive

**Comment by knaaptime** [comment]
resolved by #180
