### ISSUE TITLE
Do we have example datasets with column defining neighborhood clusters for demonstration/testing purpose? 

### ISSUE THREAD

**Issue by weikang9009** [spatialucr/geosnap#95]
Since the API has been changed for `dynamics.Transition` so that [the input data parameters are specifically "geosnap dataset object with column defining neighborhood clusters"](https://github.com/spatialucr/geosnap/blob/master/geosnap/analyze/dynamics.py#L18), do we have such example datasets for demonstration/testing purpose (similar to [libpysal.examples](https://github.com/pysal/libpysal/tree/master/libpysal/examples))?

**Comment by knaaptime** [comment]
we dont yet, but i've been doing a lot of work on the data side the last week or two so I can add a handful of examples to a new quilt package in [our bucket](https://spatialucr.quiltdata.com/)

sidenote, it looks like this uses the old `Dataset` convention, which has been refactored to `Community`. I'm still working on the internals of the second refactor of `Community`, so I'll give you a shout when its ready

**Comment by weikang9009** [comment]
Thanks for the info! I will wait for your input before proceeding on refactoring dynamics module. 

Another suggestion would be to have several small example data sets (not storing attributes - only neighborhood classifications) listed in the repo. Would be more intuitive to users.

**Comment by knaaptime** [comment]
is this resolved with #96 @weikang9009?
