### ISSUE TITLE
rework CI

### ISSUE THREAD

**Issue by knaaptime** [spatialucr/geosnap#98]
the travis config needs some love akin to the recent [reworking of pysal](https://github.com/pysal/pysal/commit/7e397bdb4c22d4e2442b4ee88bcd691d2421651d)

**Comment by sjsrey** [comment]
https://github.com/pysal/pysal/pull/1130

**Comment by knaaptime** [comment]
I gave this a shot in #97 but hitting a weird [error](https://travis-ci.com/knaaptime/geosnap/jobs/221513269 that numpy isnt installed?

**Comment by sjsrey** [comment]
```
Collecting package metadata (repodata.json): ...working... done
Solving environment: ...working... failed

PackagesNotFoundError: The following packages are not available from current channels:

  - //github.com/pysal/region.git@master
  - quilt3

Current channels:

  - https://conda.anaconda.org/conda-forge/linux-64
  - https://conda.anaconda.org/conda-forge/noarch
  - https://repo.anaconda.com/pkgs/main/linux-64
  - https://repo.anaconda.com/pkgs/main/noarch
  - https://repo.anaconda.com/pkgs/r/linux-64
  - https://repo.anaconda.com/pkgs/r/noarch

To search for alternate channels that may provide the conda package you're
looking for, navigate to

    https://anaconda.org

and use the search bar at the top of the page.


Could not find conda environment: TEST
```

**Comment by knaaptime** [comment]
ah... yeah i think you're right. quilt isnt on conda, so needs to be installed with pip. maybe that needs to be installed manually before moving to the conda step, if that's possible

the region thing i've been beating my head against and is largely because pip and conda have different conventions for specifying github dependencies (was going to raise the possibility of an EOL release at the dev meeeting tomorrow that would help solve some of these headaches)

**Comment by knaaptime** [comment]
the quilt recipe has been merged but travis is still failing, this time on spenc. no idea why

**Comment by knaaptime** [comment]
@sjsrey is it a problem that [this](https://github.com/spatialucr/geosnap/blob/2ea95336d45d751a3f08363b593a7e8190154c26/Makefile#L16) hardcodes to your user directory?

**Comment by sjsrey** [comment]
probably need to have it expand to the users home directory rather than hardcode

**Comment by knaaptime** [comment]
>the quilt recipe has been merged but travis is still failing, this time on spenc. no idea why

the recipe is merged but quilt isnt available yet on conda-forge for another couple hours so i think it's still responsible for the failure
